/* Demo mock-exam bank: 24 ORIGINAL questions written for this repository about a fictional "incident management" exam.
   Not derived from any real exam, candidate recollection, or body of knowledge.
   Shape: { d: domain, c: competency, q: stem, opts: [...], a: index of the correct option BEFORE the engine shuffles, why: explanation }.
   Run `python skills/cert-course-builder/scripts/check_distractor_bias.py skills/cert-course-builder/reference-template` after any edit. */
window.EXAM_BANK = [
/* ---------- Domain I (8) ---------- */
{ d:'I', c:'I.A', q:'An e-commerce checkout fails for about 4% of customers, and retrying the payment works. Which factor MOST directly sets the incident’s priority?', opts:['The seniority of the person who first reported the problem to the service desk','The number of engineering teams that own components along the failing path','The business impact on customers and revenue, weighed with how fast it spreads','The time of day when the first complaint reached the customer support queue'], a:2, why:'Priority follows impact and urgency. Who reported it, how many teams are involved, and when the first complaint arrived describe the report, not the harm.' },
{ d:'I', c:'I.A', q:'A monitor shows a log server’s disk at 78% and growing about 1% a day. Nobody is affected. What is the BEST classification?', opts:['Low-urgency event: schedule capacity work before the threshold becomes an outage','Critical incident: page the full on-call rotation and open a bridge immediately','Major incident: notify executives and begin hourly customer status updates now','Not an event: ignore it until a customer reports a visible symptom of the issue'], a:0, why:'No current impact and weeks of headroom make this a scheduled task. Paging or notifying executives is out of proportion, and ignoring it allows a predictable outage.' },
{ d:'I', c:'I.A', q:'Which statement correctly describes how incident priority is usually derived?', opts:['It equals impact alone, because urgency changes too quickly to be useful','It comes from the ticket’s age, with the oldest ticket always handled first','It is set by whoever raises the ticket, using their own sense of importance','It combines impact (how many, how badly) with urgency (how fast it worsens)'], a:3, why:'Impact and urgency together. Impact alone ignores a fast-growing problem, ticket age ignores harm, and reporter opinion is inconsistent across people.' },
{ d:'I', c:'I.A', q:'Two hours into a medium-severity incident, new data shows the failure now blocks payroll processing ahead of a deadline. What should the incident lead do?', opts:['Keep the original level so the incident record stays consistent with the first report','Re-classify upward, announce the change, and bring in the responders the new level needs','Wait for the formal review to adjust the level once every fact has been verified','Close this incident and open a new ticket so the history starts at the right level'], a:1, why:'Classification follows current facts. Raise it, say so, and add people. Freezing the level, waiting, or splitting the record each delays the right response.' },
{ d:'I', c:'I.B', q:'Three engineers join a call and each assumes another is leading. Which first step best restores clarity?', opts:['Name one incident lead who coordinates, then assign owners to specific workstreams','Ask all three to investigate the same hypothesis so that nothing gets missed','Escalate to the executive sponsor to decide which engineer should take the lead','Pause the response until everyone has agreed a fuller written plan of action'], a:0, why:'One lead plus explicit workstreams ends the diffusion of responsibility. Duplicated effort, escalation for a decision, and pausing for a plan all add delay.' },
{ d:'I', c:'I.B', q:'During triage a responder asks whether an alert duplicates an open incident. Why does this check matter?', opts:['It lets the desk close tickets faster so the monthly closure metric improves','It prevents parallel investigations of one problem and keeps messages consistent','It proves the original reporter deserves credit for finding the issue first','It guarantees the second alert is lower priority than the first one raised'], a:1, why:'Duplicates waste scarce attention and cause conflicting customer messages. Metrics, credit, and automatic lower priority are not reasons to check.' },
{ d:'I', c:'I.B', q:'Which responsibility belongs to the communications lead rather than the technical lead?', opts:['Choosing between a rollback and a regional failover for the failing checkout service','Reading logs to identify which deployment introduced the regression','Sending stakeholder updates on the agreed cadence while engineers keep working','Approving the emergency change that restores the affected feature'], a:2, why:'Stakeholder updates are the communications role; keeping them separate lets engineers keep working. The other three are technical or approval decisions.' },
{ d:'I', c:'I.B', q:'An on-call engineer’s shift ends mid-incident. Which handoff practice is MOST reliable?', opts:['Leave the ticket open so the next engineer can read the history afterwards','Send a short chat message saying the incident continues and who to ask','Hand over only the unresolved tasks, because finished work needs no mention','A live verbal handoff backed by notes on state, hypotheses and next steps'], a:3, why:'A live conversation allows questions and the notes preserve what was tried and believed. A passive ticket, a thin message, or open tasks alone lose context.' },

/* ---------- Domain II (9) ---------- */
{ d:'II', c:'II.A', q:'A faulty release is causing errors and a low-risk rollback is available. What is the PRIORITY?', opts:['Roll back to restore service now, then investigate once customers are unaffected','Keep the release live while engineers trace the defect so the evidence stays intact','Pause all changes for a day and review the release notes with every team','Patch forward immediately because rolling back would hide the cause of the failure'], a:0, why:'Restore first. Evidence can be captured while mitigating. Keeping the fault live, freezing change, or hurried patching each extend customer harm or add risk.' },
{ d:'II', c:'II.A', q:'Traffic to one region is failing while two other regions are healthy. Which mitigation is LEAST disruptive?', opts:['Restart every service across all regions to clear any hidden shared state','Disable the entire feature in every region until the root cause has been understood','Shift traffic from the failing region to the healthy ones while investigating','Add capacity in the failing region and wait for the errors to subside'], a:2, why:'Moving traffic removes harm without touching what works. Global restarts and global shutdowns disrupt everyone, and extra capacity does not fix a failing region.' },
{ d:'II', c:'II.A', q:'During a major incident an engineer wants to apply an untested fix directly to production. What is the BEST response?', opts:['Refuse all changes until the normal approval board can meet next week','Permit it quietly, because speed matters more than any record of the change','Allow an emergency change with a named approver, a rollback plan, and the lead informed','Require the fix to clear the full release pipeline before anyone touches production'], a:1, why:'Emergency change keeps speed and adds minimal control. A week-long wait or the full pipeline defeats the purpose, and a silent change blinds the review.' },
{ d:'II', c:'II.A', q:'A dashboard turns green after a restart. Which check best confirms the service is truly restored?', opts:['Accept the green dashboard, since it reflects the system’s own health reporting','Wait one minute and close the incident if no new alerts have been raised','Ask the engineer who restarted it whether the service seems normal again','Run a real customer transaction and watch the key metrics hold steady over time'], a:3, why:'Verify customer experience with a real transaction and steady metrics. Dashboards can lag, silence is not evidence, and a feeling is not a measurement.' },
{ d:'II', c:'II.A', q:'When should an incident move from “mitigated” to “resolved”?', opts:['When the first mitigation is applied and error rates start to fall','When the review is scheduled and the action owners have been named','When the incident lead has been awake long enough to need replacing','When service has held steady through an agreed monitoring period'], a:3, why:'Resolved means stable over an agreed period. Falling errors can reverse, scheduling a review is administrative, and fatigue is a staffing issue, not a status.' },
{ d:'II', c:'II.B', q:'Executives ask for constant updates during a long incident. Which approach BEST serves everyone?', opts:['Reply to each executive individually as soon as engineers learn anything','Agree a cadence, publish on schedule, and state when the next update will arrive','Pause updates until the cause is known to avoid sharing information that may change','Let engineers post raw investigation notes in a shared channel for anyone to read'], a:1, why:'A published cadence meets the need without pulling engineers off the work. Ad-hoc replies fragment effort, pausing creates a vacuum, and raw notes are unreadable to executives.' },
{ d:'II', c:'II.B', q:'A customer status update should differ from an engineers’ update mainly because customers need what?', opts:['A full technical diagnosis so they can see exactly which component failed','Reassurance without specifics so they do not worry about the scale of the issue','Plain-language impact, any workaround, and the expected timing of the fix','A list of every responder involved so they know who is accountable for the outage'], a:2, why:'Customers act on impact, workaround, and timing. Deep diagnosis is noise to them, vague reassurance erodes trust, and responder lists are irrelevant.' },
{ d:'II', c:'II.B', q:'The cause is unknown and no recovery estimate exists. What should the next update say?', opts:['What is known, what is not known, and when the next update will be sent','An optimistic estimate that keeps stakeholders calm until the facts improve','Nothing, since nothing new has been learned since the previous update','The leading theory, presented as the confirmed cause to show progress is being made'], a:0, why:'Honest uncertainty plus a committed next update preserves trust. Invented estimates and theories-as-fact must be retracted, and silence reads as loss of control.' },
{ d:'II', c:'II.B', q:'After service is restored, which message best completes the communication loop?', opts:['No further message, since silence signals that the problem has been fixed','A detailed apology that names the engineer whose change triggered the outage','A brief thank-you to the team, leaving customers to infer that service returned','A resolution notice that confirms impact ended and says when the review follows'], a:3, why:'Closing the loop states clearly that impact ended and what comes next. Silence leaves doubt, naming an engineer contradicts a blameless approach, and an internal thank-you tells customers nothing.' },

/* ---------- Domain III (7) ---------- */
{ d:'III', c:'III.A', q:'Which statement best describes a blameless review?', opts:['It avoids naming any person or team so that nobody feels uncomfortable','It identifies the individual whose mistake caused the incident and issues a warning','It examines why decisions made sense at the time so the system can be improved','It concentrates on the technical fault and keeps process and people out of scope'], a:2, why:'Blameless means understanding how conditions and decisions combined, then improving the system. Name-avoidance, culprit-finding, and a purely technical scope each miss that aim.' },
{ d:'III', c:'III.A', q:'A review finds that a configuration typo caused an outage. Which additional question does a good review ask?', opts:['Which engineer made the typo, and when did they last attend relevant training?','Why did the system and process allow a single typo to reach production unnoticed?','How can the team show the typo was an isolated slip that is unlikely to recur?','What penalty would deter careless changes of this kind from happening again?'], a:1, why:'The useful question is why the system allowed it. Questions about the individual, proving it was isolated, or deterrence keep attention on people instead of conditions.' },
{ d:'III', c:'III.A', q:'Why do many reviewers treat the “five whys” technique with caution for complex incidents?', opts:['It follows one causal chain and can stop at a single, convenient root cause','It needs specialist software that most teams do not have available to them','It always produces more than five causes, which makes the output unusable','It forbids questions about human factors, which are central to most failures'], a:0, why:'Complex failures have several interacting factors; one chain of whys can end wherever is easiest. The technique needs no software, can be applied with human-factor questions, and does not always yield extra causes.' },
{ d:'III', c:'III.B', q:'Which corrective action is MOST likely to be completed and to be effective?', opts:['Remind engineers to take more care when editing configuration in future','Review the configuration process soon, with the platform and release teams as joint owners','Add a pre-deploy check that rejects invalid configuration, one owner, due in two weeks','Improve monitoring and documentation where needed, tracked as an ongoing effort'], a:2, why:'It changes the system, has one owner and a date, and can be verified. Reminders rely on memory, joint ownership diffuses responsibility, and open-ended efforts never finish.' },
{ d:'III', c:'III.B', q:'A team marks a corrective action “done” when its code merges. What is the stronger completion standard?', opts:['Accept the merge, since peer-reviewed code shows that the work has been carried out','Close it when the owner reports in the next meeting that it is finished','Close it once the review document links to the merged pull request','Confirm it works in production, for example with a test that exercises the failure'], a:3, why:'The point of an action is reduced risk, so completion needs evidence of that. A merge, a verbal report, or a link shows only that something was done, not that it works.' },
{ d:'III', c:'III.B', q:'Actions from past reviews keep stalling. Which practice BEST improves follow-through?', opts:['Store them only in the review document, where all the context is available','Track them in the normal work queue with owners, due dates, and an overdue review','Limit each review to one action so that the team can concentrate on finishing it','Assign every action to the incident lead so that one person is accountable'], a:1, why:'Actions in the real work queue, with owners and dates and a look at what is overdue, get done. A document is easy to forget, one action loses learning, and one owner for everything creates a bottleneck.' },
{ d:'III', c:'III.B', q:'A review produces twelve proposed actions. How should the team decide which to commit to?', opts:['Commit to all twelve so that nobody can say a suggestion was ignored','Choose the cheapest actions first because quick wins build momentum','Defer the decision until the next incident shows which of the actions would have mattered most','Rank by risk reduction against effort, commit to a few, and explain what is declined'], a:3, why:'Prioritised, honest commitments get finished and keep trust. Committing to everything guarantees failure, cheapest-first ignores risk, and deferring wastes the learning.' }
];
